name: 'nazwa-akcji'
description: 'To jest mój pierwszy action'
branding:
  icon: 'book-open'
  color: 'blue'
inputs:
  jakies-cos:
    description: 'Jakies cos'
    required: true
    default: 'A no tak'
outputs:
  wynik:
    description: 'Wynik'
    # value: ${{ steps.testing.inputs.jakies-cos }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.jakies-cos }}
    - 'inny'
  # entrypoint: 'my_app.py'
