name: 'jakies-cos'
description: 'To jest mój pierwszy action'
inputs:
  jakies-cos:
    description: 'Jakies cos'
    required: true
    default: 'A no tak'
outputs:
  wynik:
    description: 'Wynik'
    # value: ${{ steps.testing.inputs.jakies-cos }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.jakies-cos }}
