on: ["push"]

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "My Step"
        env:
          MY_ACTION: ${{ github.action}}
        run: |
          echo "Hello! $MY_ACTION"
          echo "Hello! ${{ github.action }}"
      - name: "My Step 2"
        env:
          MY_ACTION: ${{ github.action}}
        run: |
          echo "Hello! $MY_ACTION"
          echo "Hello! ${{ github.action }}"
      - name: "My Step 3"
        id: dupa
        env:
          MY_ACTION: ${{ github.action}}
        run: |
          echo "Hello! $MY_ACTION"
          echo "Hello! ${{ github.action }}"