on: ['push']

jobs:
  jakis_job:
    runs-on: ubuntu-latest
    name: A job
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install Python dependencies
        # uses: py-actions/py-dependency-install@v4
        # with:
        #   path: "requirements.txt"
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Just testing step
        id: testing
        uses: apecmat/Github-Examples@main
        with:
          args: 'jakies-cos=A no jednak na pewno tak'
      - name: A teraz output
        run: echo "Wynik ${{ steps.testing.outputs.wynik }}"
