on: ['push']

jobs:
  jakis_job:
    runs-on: ubuntu-latest
    name: A job
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Just testing step
        id: testing
        uses: apecmat/Github-Examples@main
        with:
          args: 'jakies-cos=A no jednak na pewno tak'
      - name: A teraz output
        run: echo "Wynik ${{ steps.testing.outputs.wynik }}"
